// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  datasource: {
    // Migrations must bypass the connection pooler. On Supabase, DATABASE_URL
    // is the pgBouncer (6543) URL which cannot run DDL — DIRECT_URL (5432) is
    // used when present, falling back to DATABASE_URL for local dev.
    url: process.env["DIRECT_URL"] || process.env["DATABASE_URL"],
  },
});
